In [1]:
import torch

In [2]:
######### zeros ########
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [3]:
######### ones ###########
i = torch.ones((5,3))
print(i)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
torch.abs(torch.tensor(5.5))

tensor(5.5000)

In [11]:
a = torch.ones(4,3,2)
print(a)

b = torch.rand(3,2)
print(b)

c = b * a
print(b)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[0.3834, 0.4351],
        [0.5400, 0.7771],
        [0.9542, 0.2415]])
tensor([[0.3834, 0.4351],
        [0.5400, 0.7771],
        [0.9542, 0.2415]])


### More math with Tensors

In [17]:
a = torch.rand(2,4) * 2
print(a)

tensor([[1.8784, 0.7143, 1.0233, 0.4278],
        [0.2330, 1.9138, 0.5607, 0.8980]])


In [18]:
torch.abs(a)

tensor([[1.8784, 0.7143, 1.0233, 0.4278],
        [0.2330, 1.9138, 0.5607, 0.8980]])

In [19]:
torch.ceil(a)

tensor([[2., 1., 2., 1.],
        [1., 2., 1., 1.]])

In [20]:
torch.floor(a)

tensor([[1., 0., 1., 0.],
        [0., 1., 0., 0.]])

In [21]:
torch.clamp(a, -0.5, 0.5) ## limit the values between these range

tensor([[0.5000, 0.5000, 0.5000, 0.4278],
        [0.2330, 0.5000, 0.5000, 0.5000]])

In [26]:
############## trigonometric ###############
angles = torch.tensor([0, torch.math.pi / 4, torch.math.pi / 2, 3 * torch.math.pi / 4, 1])
print(angles)

tensor([0.0000, 0.7854, 1.5708, 2.3562, 1.0000])


In [27]:
sines = torch.sin(angles)
print(sines)

tensor([0.0000, 0.7071, 1.0000, 0.7071, 0.8415])


In [29]:
inverses = torch.asin(sines)
print(inverses)

tensor([0.0000, 0.7854, 1.5708, 0.7854, 1.0000])


In [ ]:
################## bitwise ##########
b = torch.tensor